# Configure your servers for Azumatt's FastLink mod in this file.
# Servers are automatically sorted alphabetically when shown in the list.
# This file live updates the in-game listing. Feel free to change it while in the main menu.

<color=green>Sketafuls Modded Adventure</color>:
  address: server.sketaful.se
  port: 2500
  password: oldies
  iswhitelisted: false
  iscrossplay: false
