
Deer Soul Power:
  slot: legs
  gem: Deer Soul Gem
  power:
    value: [10, 15, 20, 25, 30]
  unique: None

Neck Soul Power:
  slot: legs
  gem: Neck Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: None

Boar Soul Power:
  slot: all
  gem: Boar Soul Gem
  power:
    value: [3, 5, 7, 9, 11]
  unique: None

Greydwarf Soul Power:
  slot: all
  gem: Greydwarf Soul Gem
  power:
    value: [3, 6, 9, 12, 15]
    cooldown: [60, 50, 45, 40, 35]
  unique: Item

GreydwarfBrute Soul Power:
  slot: all
  gem: GreydwarfBrute Soul Gem
  power:
    value: [0.4, 0.7, 1, 1.3, 1.6]
  unique: Gem

GreydwarfShaman Soul Power:
  slot: all
  gem: GreydwarfShaman Soul Gem
  power:
    value: [26, 25, 24, 23, 20]
  unique: Gem

Troll Soul Power:
  slot: weapon
  gem: Troll Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
    chance: [30, 35, 40, 45, 50]
  unique: None

Skeleton Soul Power:
  slot: all
  gem: Skeleton Soul Gem
  power:
    chance: [7, 9, 11, 13, 15]
    value: [3, 2, 2, 1, 0]
  unique: Gem

Draugr Soul Power:
  slot: shield
  gem: Draugr Soul Gem
  power:
    value: [20, 30, 40, 50, 60]
  unique: Gem

Blob Soul Power:
  slot: legs
  gem: Blob Soul Gem
  power:
    value: [0.3, 0.8, 1.5, 2.2, 2.9]
  unique: None

Leech Soul Power:
  slot: weapon
  gem: Leech Soul Gem
  power:
    value: [1, 1.5, 2, 2.5, 3]
  unique: None

Wraith Soul Power:
  slot: all
  gem: Wraith Soul Gem
  power:
    cooldown: [30, 26, 22, 18, 14]
  unique: Gem

Abomination Soul Power:
  slot: all
  gem: Abomination Soul Gem
  power:
    value: [30, 40, 50, 60, 70]
    cooldown: [30, 28, 26, 24, 22]
  unique: Gem

Wolf Soul Power:
  slot: [head, chest, legs, weapon]
  gem: Wolf Soul Gem
  power:
    value: [9, 12, 15, 18, 21]
  unique: Item

Bat Soul Power:
  slot: weapon
  gem: Bat Soul Gem
  power:
    value: [1, 1.5, 2, 2.5, 3]
  unique: None

Fenring Soul Power:
  slot: weapon
  gem: Fenring Soul Gem
  power:
    value: [1, 2, 3, 4, 5]
  unique: None

Cultist Soul Power:
  slot: head
  gem: Cultist Soul Gem
  power:
    value: [20, 35, 50, 65, 80]
    cooldown: [35, 30, 25, 20, 15]
  unique: Gem

Ulv Soul Power:
  slot: all
  gem: Ulv Soul Gem
  power:
    cooldown: [20, 18, 16, 14, 12]
  unique: Gem

StoneGolem Soul Power:
  slot: all
  gem: StoneGolem Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: Gem

Hatchling Soul Power:
  slot: weapon
  gem: Hatchling Soul Gem
  power:
    value: [150, 200, 250, 300, 350]
  unique: Gem

Goblin Soul Power:
  slot: weapon
  gem: Goblin Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: Gem

Deathsquito Soul Power:
  slot: weapon
  gem: Deathsquito Soul Gem
  power:
    value: [5, 7, 9, 11, 13]
  unique: Gem

Lox Soul Power:
  slot: [head, chest, legs, weapon, cloak]
  gem: Lox Soul Gem
  power:
    value: [10, 20, 30, 40, 50]
  unique: Gem

GoblinBrute Soul Power:
  slot: [head, chest, legs, cloak]
  gem: GoblinBrute Soul Gem
  power:
    value: [15, 20, 25, 30, 35]
  unique: Gem

GoblinShaman Soul Power:
  slot: [head, chest, legs, cloak]
  gem: GoblinShaman Soul Gem
  power:
    value: [10, 15, 20, 25, 30]
  unique: Gem

TarBlob Soul Power:
  slot: all
  gem: TarBlob Soul Gem
  power:
    duration: [6, 7, 8, 9, 10]
    cooldown: [32, 30, 28, 26, 24]
  unique: Gem

Surtling Soul Power:
  slot: weapon
  gem: Surtling Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
    cooldown: [60, 50, 45, 40, 35]
  unique: Gem

Serpent Soul Power:
  slot: shield
  gem: Serpent Soul Gem
  power:
    value: [25, 50, 75, 100, 125]
  unique: Gem

Hare Soul Power:
  slot: weapon
  gem: Hare Soul Gem
  power:
    value: [4, 8, 12, 16, 20]
  unique: None

Dverger Soul Power:
  slot: all
  gem: Dverger Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: Item

Dverger Fire Mage Soul Power:
  slot: all
  gem: Dverger Fire Mage Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: Item

Dverger Blood Mage Soul Power:
  slot: all
  gem: Dverger Blood Mage Soul Gem
  power:
    value: [10, 15, 20, 25, 30]
  unique: Item

Dverger Ice Mage Soul Power:
  slot: all
  gem: Dverger Ice Mage Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: Item

Tick Soul Power:
  slot: all
  gem: Tick Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: Item

Gjall Soul Power:
  slot: all
  gem: Gjall Soul Gem
  power:
    value: [3, 6, 9, 12, 15]
  unique: Item

Seeker Soul Power:
  slot: all
  gem: Seeker Soul Gem
  power:
    value: [5, 10, 15, 20, 25]
  unique: Item

Seeker Brute Soul Power:
  slot: all
  gem: Seeker Brute Soul Gem
  power:
    value: 1
  unique: Gem

Eikthyr Soul Power:
  slot: all
  gem: Eikthyr Soul Gem
  power:
    value: [1, 2, 3, 4, 5]
  unique: Gem

Elder Soul Power:
  slot: all
  gem: Elder Soul Gem
  power:
    value: [25, 24, 23, 22, 21]
  unique: Gem

Bonemass Soul Power:
  slot: all
  gem: Bonemass Soul Gem
  power:
    value: 40
  unique: Gem

Moder Soul Power:
  slot: all
  gem: Moder Soul Gem
  power:
    value: [20, 30, 40, 50, 60]
  unique: Gem

Yagluth Soul Power:
  slot: all
  gem: Yagluth Soul Gem
  power:
    value: 40
  unique: Gem

The Queen Soul Power:
  slot: all
  gem: The Queen Soul Gem
  power:
    value: 20
  unique: Gem
